# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tworgy-ruby-ext}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mat Holroyd"]
  s.date = %q{2009-11-01}
  s.description = %q{fdsfsad}
  s.email = %q{code@tworgy.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/tworgy-ruby-ext.rb",
     "lib/tworgy/recursively.rb",
     "lib/tworgy/standard_extensions.rb",
     "lib/tworgy/tmail.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/tworgy-ruby-ext_spec.rb"
  ]
  s.homepage = %q{http://github.com/matholroyd/tworgy-ruby-ext}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Handy Ruby extensions}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/tworgy-ruby-ext_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

